Top section
bogachenkopetr/startup pull request #1
Opened 2020-01-24 11:54 UTC by bogachenkopetr

2020-01-24 12:03 UTC, abahachenka commented
1. установить шрифты согласно макету
2. подобрать наиболее часто используемы брейкпоинты для media-запросов
3. сделать шаблон адаптивным под мобильное разрешение

2020-01-24 12:03 UTC, abahachenka requested changes

2020-01-24 12:03 UTC, abahachenka commented on index.html
> +   <div class="top_section">
top_section переделать в тег section

2020-01-24 12:03 UTC, abahachenka commented on index.html
> +                    <div class="my_topnav">
my_topnav - переделать с помощью ul > li, класс my_topnav заменить на более смысловое

2020-01-24 12:03 UTC, abahachenka commented on index.html
> +           <header>
header должно быть сделано с помощью flex, без float

2020-01-24 12:03 UTC, abahachenka commented on index.html
> +               <a href="#" class="header_logo">Startup</a>
Все ссылки должны иметь атрибут title

2020-01-25 07:45 UTC, bogachenkopetr reviewed
внес изменения по комментариям

2020-01-25 07:45 UTC, bogachenkopetr commented on index.html
> +   <div class="top_section">
сделал

2020-01-31 20:16 UTC, abahachenka requested changes

2020-01-31 20:16 UTC, abahachenka commented on index.html
> +    <title>maket_home</title>
Поменяй на человекопонятный  тайтл. Вставь например Startup

2020-01-31 20:16 UTC, abahachenka commented on index.html
> +                    <form class="topnav_button">
Форма не нужна. Нужен один button для семантики. Представь, что твоим сайтом пользуется слепой человек. Для него разработаны специальные программы, которые озвучивают, какие элементы находятся на сайта и на какие можно нажать. Вот поэтому здесь и нужен button, а не просто иконка или div. А в форме нет необходимости, так как мы не отправляем никакие данные.

Также, имя класса слишком общее. Эта кнопка будет открывать мобильное меню, поэтому имя нужно подобрать такое, чтобы отражало эту функцию.

2020-01-31 20:16 UTC, abahachenka commented on style.css
> +    font-family: 'montserratbold';
Имя шрифта не должно содержать название стиля. Здесь важно только семейство - Monserrat.
Bold прописывается в `font-style`

2020-01-31 20:16 UTC, abahachenka commented on style.css
> +    font-family: 'montserratregular';
Здесь тоже самое что и выше. Только regular никак прописывать не нужно. Оно соответствует значению `font-style: normal`

2020-01-31 20:16 UTC, abahachenka commented on style.css
> +    display: inline-block;
Это flex-item. Он лежит в хедере с отображением flex. Inline-block убирай - это из другой оперы.

2020-01-31 20:16 UTC, abahachenka commented on style.css
> +    display: none;
В этом блоке оставь только последний display: none и напиши комментарий что ты скрываешь его на мобильном экране.

2020-01-31 20:16 UTC, abahachenka commented on style.css
> +}
Эти стили здесь не нужны, так как они наследуются из мобильного разрешения

2020-02-02 09:04 UTC, bogachenkopetr commented
внес изменения по комментариям

2020-02-04 19:31 UTC, abahachenka requested changes

2020-02-04 19:31 UTC, abahachenka commented on style.css
> +
убрать пустую строчку

2020-02-04 19:31 UTC, abahachenka commented on style.css
> +
убрать пустую строчку

2020-02-04 19:31 UTC, abahachenka commented on style.css
> +@font-face {
Поменяй местами этот font-face со слудующим местами, чтобы сначала шли стили для normal, а потом для bold

2020-02-04 19:31 UTC, abahachenka commented on style.css
> +    font-size: 22px;/*24px на 22px*/
Непонятные комментарии. Либо поясни их либо удали

2020-02-04 19:31 UTC, abahachenka commented on style.css
> +.burger_menu{  /*бургер меню*/
Как по мне от комментария никакой пользы. Он просто дублирует название класса

2020-02-04 19:31 UTC, abahachenka commented on style.css
> +}
Разобраться с комментариями. Выровнять пробелы.

2020-02-04 19:31 UTC, abahachenka commented on style.css
> +}
Нужно сдвинуть содержимое клавишей Tab

2020-02-04 19:31 UTC, abahachenka commented on style.css
> +
Убрать лишние строки

2020-02-04 19:31 UTC, abahachenka commented on style.css
> +}
Добавить табуляцию

2020-02-04 19:31 UTC, abahachenka commented on index.html
> +                      <button class="burger_menu">&#9776;</button>
Настроить правильную табуляцию

2020-02-04 19:31 UTC, abahachenka commented on style.css
> +    height: 770px;
Слишком большая высота для мобильного расширения. Блок welcome уезжает вниз на мобиле. Можешь проверить если включишь какой-нибудь из режимов конкретного мобильного. Здесь бы очень хорошо подошла высота 100vmax = 100% наибольшего из значений высоты или ширины экрана.

2020-02-04 19:31 UTC, abahachenka commented on style.css
> +    margin-bottom: 50px;
На самом большом экране эти отступы вдруг стали меньше предыдущих.Перенеси их в мобильные стили и можешь больше не менять в других media-запросах.

2020-02-04 19:31 UTC, abahachenka commented on style.css
> +.top_welcome a{
Этой кнопке нужен  display: inline-block.

2020-02-05 15:50 UTC, bogachenkopetr commented on style.css
> +.top_welcome a{
внес изменения по комментариям

2020-02-05 19:32 UTC, abahachenka approved these changes

2020-02-05 19:32 UTC, merged