Services
bogachenkopetr/startup pull request #2
Opened 2020-02-06 19:16 UTC by bogachenkopetr

2020-02-08 09:02 UTC, abahachenka requested changes

2020-02-08 09:02 UTC, abahachenka commented on index.html
> +        <div class="main_section_services">
Новая логическая секция - нужен тег section

2020-02-08 09:02 UTC, abahachenka commented on index.html
> +                <h1>SERVICES</h1>
В данном случае, не следует имееть более одного `h1` на странице. Исключения бывают, но в них лучше разбираются сеошники. В большинстве случаев, тебе нужно следовать золотому правилу: "не больше одного `h1` на странице".  
Читай https://sitechecker.pro/ru/h1-tag

2020-02-08 09:02 UTC, abahachenka commented on index.html
> +                </div>
Данную полоску лучше добавить предназначенным для этого тегом `hr,` но никак не картинкой!

2020-02-08 09:02 UTC, abahachenka commented on index.html
> +                    <div class="clean">
Следует улучшить имена классов, так как в данном случае они не описывают реальное предназначение и фунциональность блока. Дословный перевод "главный чистый" -> "чистый". Называй свои классы согласно тому, что они описывают, например: список сервисов, сервис и т.д.

2020-02-08 09:02 UTC, abahachenka commented on index.html
> +                        <div class="icon">
icon - слишком общее название. Может вступить в конфликт со стилями в других блоках. Если здесь не применяются стили, которые действительно общие для всех иконок, которые могут использоваться и в других местах, то лучше давай более конкретное имя, например: "service_icon".

2020-02-08 09:02 UTC, abahachenka commented on index.html
> +                        </ul>
Список здесь совсем не подходит. Это обычный абзац.

2020-02-08 09:02 UTC, abahachenka commented on style.css
> +/*----------------------------------*/
Эту полоску можешь убрать, я ее добавляла для тебя, чтобы ты увидел, где добавились стили.

2020-02-08 09:02 UTC, abahachenka commented on style.css
> +    height: 100vh;
Здесь высоту ставить вообще не обязательно, так как она будет автоматически регулироваться в зависимости от содержимого

2020-02-12 09:19 UTC, bogachenkopetr commented
внес частично изменения по комментариям

2020-02-12 12:54 UTC, abahachenka requested changes

2020-02-12 12:54 UTC, abahachenka commented on index.html
> +                </div>-->
Закончишь с полоской - убери этот код вообще

2020-02-12 12:54 UTC, abahachenka commented on index.html
> +                            harum ex magni, dicta impedit. Lorem ipsum.<br>
Br-ки тут не нужны вообще

2020-02-12 12:54 UTC, abahachenka commented on index.html
> +                            harum ex magni, dicta impedit. Lorem ipsum.<br>
И тут убери br

2020-02-12 12:54 UTC, abahachenka commented on index.html
> +                            harum ex magni, dicta impedit. Lorem ipsum.<br>
И тут убери br

2020-02-12 12:54 UTC, abahachenka commented on style.css
> +        height: 580px;
Высота должна быть автоматической

2020-02-12 12:54 UTC, abahachenka commented on style.css
> +        size: 5px;/*??????????*/
?????

2020-02-12 12:54 UTC, abahachenka commented on style.css
> +        size: 5px;/*??????????*/
Во-первый, задавать стили начинай с мобильного разрешения. Во-вторых, ты здесь обращаешься по классу, который не присвоен никакому элементу. В-третьих, size точно работать не будет. Элемент hr это по сути обычный блочный элемент, прямоугольник, у которого заданы бордеры по всем сторонам, но внутри прямоугольника пусто и поэтому бордеры склеиваются все вместе, визуально образуя одну полоску. Чтобы реализовать твою задачу, нужно задать ширину по макету, выровнять по-центру и задать border нужной толщины. Чтобы все отображалось корректно, советую вначале обнулить все бордеры через `border: 0`, а следующей строчкой написать `border-top: [толщина] solid [цвет]`.

2020-02-12 12:54 UTC, abahachenka commented on index.html
> +                <div class="blocks_services">
Ты уж извини, что я тебя задалбываю, но я хочу добиться, чтобы ты придумывал толковые имена своим классам, и чтобы с тебя потом на работе не стебались. Переименуй тут в `service_list`

2020-02-12 12:54 UTC, abahachenka commented on index.html
> +                    <div class="block_one">
А тут в `service_item`. Название блок один не намного лучше, если бы у тебя было div1

2020-02-12 16:37 UTC, bogachenkopetr commented
внес исправления в секцию services

2020-02-13 07:02 UTC, merged