Наработки из ветки start
bogachenkopetr/startup pull request #3
Opened 2020-02-13 12:42 UTC by bogachenkopetr

2020-02-16 18:28 UTC, abahachenka requested changes

2020-02-16 18:28 UTC, abahachenka commented on index.html
> +                <div class="ubout_us_title">
Во-первых, тут нужен тег `header`. Во-вторых, не `ubout`, а `about`.

2020-02-16 18:28 UTC, abahachenka commented on index.html
> +                    <li><img src="img/man1.png" alt="man1.png">MD. KHALIL UDDIN<br><span>Head of Ideas</span></li>
Здесь тебе нужно надпись под фото обернуть в отдельный тег, чтобы он отображался как блок и уходил на новую строку. Сейчас все немножко поломано. 
<img width="660" alt="Screen Shot 2020-02-16 at 21 18 45" src="https://user-images.githubusercontent.com/53353277/74610234-66850700-5102-11ea-86bd-70b674d12178.png">

2020-02-16 18:28 UTC, abahachenka commented on index.html
> +                    <li><img src="img/man1.png" alt="man1.png">MD. KHALIL UDDIN<br><span>Head of Ideas</span></li>
И еще, первое фото не должно отличаться от остальных. Затемнение с иконками это эффект при наведении.

2020-02-16 18:28 UTC, abahachenka commented on style.css
> +    width: 101px;
В данном случае выбран не совсем верный подход для регулирования ширины элементов списка. Ширина должна регулироваться у `li`, а `img` должно принимать 100% ширины `li`. Высота у картинок не должна задаваться, если конечно ты все картинки вырезал одинаковых размеров.

2020-02-21 20:18 UTC, abahachenka commented
Проблемы с шириной фото. При изменении ширины страницы все ломается. Нужно сделать фотки гибкими.
<img width="836" alt="Screen Shot 2020-02-21 at 23 16 19" src="https://user-images.githubusercontent.com/53353277/75068548-68830780-5500-11ea-8cdf-f7277daadd89.png">
<img width="1110" alt="Screen Shot 2020-02-21 at 23 16 11" src="https://user-images.githubusercontent.com/53353277/75068556-6e78e880-5500-11ea-91d8-b8a030624293.png">

2020-02-21 20:19 UTC, abahachenka commented
Для мобильного разрешения пока скрой затемнение. Я подумаю как можно отобразить ссылки
<img width="873" alt="Screen Shot 2020-02-21 at 23 16 26" src="https://user-images.githubusercontent.com/53353277/75068629-98caa600-5500-11ea-8565-ce89ae259d17.png">

2020-02-23 08:08 UTC, bogachenkopetr commented
внес исправления по комментариям

2020-02-24 20:06 UTC, merged