Добавила наработки latest works из ветки start
bogachenkopetr/startup pull request #4
Opened 2020-02-25 05:33 UTC by bogachenkopetr

2020-02-28 20:29 UTC, abahachenka requested changes

2020-02-28 20:29 UTC, abahachenka commented on index.html
> +                    </header>
Неправильное форматирование. TAB назад

2020-02-28 20:29 UTC, abahachenka commented on style.css
> +    height: 1380px;
Удалить. Высота автоматическая.

2020-02-28 20:29 UTC, abahachenka commented on style.css
> +    margin-bottom: 30px;
Объедини в margin одной строкой

2020-02-28 20:29 UTC, abahachenka commented on style.css
> +    margin-right: 30px;
объедини в одну строку

2020-02-28 20:29 UTC, abahachenka commented on style.css
> +    margin-right: 0;
Не понимаю, что здесь делает right

2020-02-28 20:29 UTC, abahachenka commented on style.css
> +    font-weight: normal;
Эта строчка нужна?

2020-02-28 20:29 UTC, abahachenka commented on style.css
> +    color: red;
Ненужная строчка. Перезаписывается ниже по коду

2020-02-28 20:29 UTC, abahachenka commented on style.css
> +}
Добавь эффект на hover

2020-02-28 20:29 UTC, abahachenka commented on style.css
> +.latest_works_photo_section h2{
Класс, к которому привязаны стили для `h2` и `p` лучше выбрать тот, что поближе, например, latest_works_dark

2020-02-28 20:29 UTC, abahachenka commented on style.css
> +.latest_works_title h1{
Заголовок отличается от всех предыдущих. Возможно, он должен быть нежирным

2020-02-28 20:29 UTC, abahachenka commented on style.css
> +    margin-bottom: 15px;
Попробуй тут написать 4%

2020-02-28 20:29 UTC, abahachenka commented on style.css
> +        margin-bottom: 40px;
а тут пусть наследуются  4%

2020-02-29 09:51 UTC, bogachenkopetr commented
внес изменения по комментам

2020-02-29 11:10 UTC, abahachenka approved these changes

2020-02-29 11:10 UTC, merged