Добавила наработки из ветки start
bogachenkopetr/startup pull request #5
Opened 2020-02-29 12:30 UTC by bogachenkopetr

2020-03-01 19:53 UTC, abahachenka requested changes
Визуально выглядит очень красиво, аккуратно и качественно. Но с кодом нужно еще поработать. Ставлю 4 с плюсом (по 5-ти бальной шкале).

2020-03-01 19:53 UTC, abahachenka commented on index.html
> +                <div class="our_work_dark">
Этот блок статичен. Текст и затемнение должны быть видны сразу, а не при наведении.  Убирай "our_work_dark". Название придумал!!! наша работа темная)))))

2020-03-01 19:53 UTC, abahachenka commented on index.html
> +                    <a class="our_work_button_center" href="#">GET IN TOUCH</a>
Вот тут hover для кнопки приветствуется

2020-03-01 19:53 UTC, abahachenka commented on index.html
> +                <div class="startup_ideas_wrapper">
Здесь должны быть общие классы для всех публикаций блога. Представим, что их может быть и 10 и 20, ты же не будешь для каждого придумывать свои имена классов и копи-пастить одни и те же стили?

К разметке тоже есть вопросы. Коду нужно добавить семантики. Одна статья - это article. Для даты должен быть указан аттрибут datetime.

2020-03-01 19:53 UTC, abahachenka commented on index.html
> +                    <h1>RECENT BLOG POSTS</h1>
h1 только один на страницу! Здесь должен быть h2

2020-03-01 19:53 UTC, abahachenka commented on index.html
> +                            <h2>STARTUP IDEAS NEEDS TO BE FUNDED </h2>
Так как заголовок всей секции h2, здесь будет ниже по иерархии - h3

2020-03-01 19:53 UTC, abahachenka commented on index.html
> +                            <h3>By <span class="startup_red">Khalil</span> Uddin in <span class="startup_red">Development</span></h3>
Авторство не относится к заголовку. Можешь здесь использовать просто `p`

2020-03-01 19:53 UTC, abahachenka commented on index.html
> +                        <span>READ MORE</span>
Это ссылка на полную статью

2020-03-01 19:53 UTC, abahachenka commented on style.css
> +    height:370px; /*не знаю как уменшить*/
Ты можешь задавать любую высоту. А картинку попробуй растягивать/сужать с помощью параметра background-size:cover.

2020-03-01 19:53 UTC, abahachenka commented on style.css
> +    font-weight: normal;
Объединить в одну строчку font

2020-03-01 19:53 UTC, abahachenka commented on style.css
> +}
Не-не. Это убираем. Текст виден сразу.

2020-03-01 19:53 UTC, abahachenka commented on style.css
> +.recent_blog_title h1{
Не забудь поменять на h2

2020-03-01 19:53 UTC, abahachenka commented on style.css
> +    font-family:'roboto_slab', serif;
В одну строчку

2020-03-01 19:53 UTC, abahachenka commented on style.css
> +.startup_date_18{
А что делать если дата 20 или 1? И не октября, а февраля?

2020-03-01 19:53 UTC, abahachenka commented on style.css
> +.startup_ideas_title h2{
Если бы ты повесил этот класс на сам заголовок, то тебе не пришлось бы менять каждый раз теги.

2020-03-01 19:53 UTC, abahachenka commented on style.css
> +.startup_ideas_title h2:hover{
Неа, hover на ссылке должен быть

2020-03-01 19:53 UTC, abahachenka commented on index.html
> +                            <h2>STARTUP IDEAS NEEDS TO BE FUNDED </h2>
В заголовок еще должна быть вложена ссылка

2020-03-01 19:53 UTC, abahachenka commented on style.css
> +    font-size: 12px;
Font одной строкой

2020-03-01 19:53 UTC, abahachenka commented on style.css
> +    font-size: 10px;
Font одной строкой

2020-03-01 19:53 UTC, abahachenka commented on style.css
> +.startup_date_oct{
Не oct, а лучше замени на month

2020-03-01 19:53 UTC, abahachenka commented on style.css
> +.startup_ideas_title h3{
Автор не заголовок. Не забудь поменять здесь.

2020-03-01 19:53 UTC, abahachenka commented on style.css
> +    margin-top: 40px;
Дальше я даже не проверяю. Тут по сути все повторяется. Так не должно быть. Разработай такие классы, чтобы можно было навесить хоть на 100 статей одновременно.

2020-03-02 13:56 UTC, bogachenkopetr commented
внес исправления по замечаниям

2020-03-03 10:38 UTC, abahachenka requested changes

2020-03-03 10:38 UTC, abahachenka commented on index.html
> +        <div class="main_section_our_work">
тег section

2020-03-03 10:38 UTC, abahachenka commented on index.html
> +                <div class="our_work_wrapper">
Этот div лишний. Лучше перекинь стили на main_section_our_work

2020-03-03 10:38 UTC, abahachenka commented on index.html
> +                    <h1>Do you like OUR WORK so far?<br>
Первое предложение переделать на h2, а второе - на p

2020-03-03 10:38 UTC, abahachenka commented on index.html
> +        <div class="main_section_recent_blog">
тег section

2020-03-03 10:38 UTC, abahachenka commented on index.html
> +                            </ul>
Тег time

2020-03-03 10:38 UTC, abahachenka commented on index.html
> +                <div class="startup_ideas_wrapper">
Article

2020-03-03 10:38 UTC, abahachenka commented on index.html
> +                    </div>
Header

2020-03-03 10:38 UTC, abahachenka commented on index.html
> +                            <h3>STARTUP IDEAS NEEDS TO BE FUNDED </h3>
Ссылка

2020-03-03 10:38 UTC, abahachenka commented on index.html
> +                            <h4>By <span class="startup_red">Khalil</span> Uddin in <span class="startup_red">Development</span></h4>
Не заголовок! Лучше `p`

2020-03-04 07:23 UTC, bogachenkopetr commented
внес исправления по комментариям

2020-03-04 11:54 UTC, abahachenka approved these changes

2020-03-04 11:54 UTC, merged